version: "3"
services:
  backend:
    container_name: mrs-backend
    build:
      context: ./backend/
    ports:
      - "5008:5008"
    volumes:
      - ./backend/:/src
    environment:
      - CORPUS=spanish_corpus.csv
      - APIPORT=5000
      - WEBWORKERS=1
  frontend:
    container_name: mrs-frontend
    build:
      context: ./frontend/
    ports:
      - "3008:3008"
    volumes:
      - ./frontend/:/src
